import React from "react";
import "./Commercialcapex.css";
import { FaCoins, FaBolt } from "react-icons/fa";

const Commercialcapex = () => {
  const data = [
    {
      category: "Investment",
      capex: "You have to make 100% upfront investment.",
      opex: "You pay only for the electricity generated by the plant."
    },
    {
      category: "Ownership Rights",
      capex: "You are the owner of the system.",
      opex: "Third-party developer owns the system during contract period."
    },
    {
      category: "Electricity Tariff",
      capex: "Tariff depends on grid rate.",
      opex: "Developer sets tariff, usually lower than grid rate."
    },
    {
      category: "Operation & Maintenance",
      capex: "You are responsible for O&M.",
      opex: "Developer handles all O&M responsibilities."
    },
    {
      category: "Payback Period",
      capex: "Shorter payback (5–6 years).",
      opex: "Longer payback (up to 10 years)."
    },
    {
      category: "Tax Benefits",
      capex: "You can claim tax benefits and rebates.",
      opex: "Developer claims tax benefits."
    },
    {
      category: "Financial Risk",
      capex: "You bear all financial risks.",
      opex: "Financial risk is borne by developer."
    },
    {
      category: "Upfront Cost",
      capex: "High initial investment required.",
      opex: "No upfront cost. Monthly payment model."
    }
  ];

  return (
    <section className="Commercialcapex-wrapper">
      <div className="Commercialcapex-container">

        <div className="Commercialcapex-header">
          <span className="Commercialcapex-badge">
            Commercial Solar Financing
          </span>
          <h2>
            What is the <span>CapEx</span> & <span>OpEx</span> Model?
          </h2>
          <p>
            CapEx (Capital Expenditure) and OpEx (Operational Expenditure)
            are two popular financing models used in commercial solar
            installations. Choose the right model based on your financial
            strategy and long-term goals.
          </p>
        </div>

        {/* Desktop Table */}
        <div className="Commercialcapex-table-wrapper">
          <table className="Commercialcapex-table">
            <thead>
              <tr>
                <th>Category</th>
                <th><FaCoins style={{marginRight:"8px"}} /> CapEx Model</th>
                <th><FaBolt style={{marginRight:"8px"}} /> OpEx Model</th>
              </tr>
            </thead>
            <tbody>
              {data.map((item, index) => (
                <tr key={index}>
                  <td className="Commercialcapex-category">{item.category}</td>
                  <td>{item.capex}</td>
                  <td>{item.opex}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Cards */}
        <div className="Commercialcapex-mobile">
          {data.map((item, index) => (
            <div className="Commercialcapex-card" key={index}>
              <h4>{item.category}</h4>
              <div className="Commercialcapex-card-content">
                <div className="capex-box">
                  <strong>CapEx Model</strong>
                  <p>{item.capex}</p>
                </div>
                <div className="opex-box">
                  <strong>OpEx Model</strong>
                  <p>{item.opex}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
};

export default Commercialcapex;